#!/bin/bash

URI=$(grep ^uri /etc/ldap/ldap.conf |awk '{print $2}' |awk -F, '{print $1}')
BASE=$(grep ^base /etc/ldap/ldap.conf |awk '{print $2}')

ldapsearch -x -H ${URI} -b ${BASE} "(&(objectClass=posixAccount)(uid=$1))" sshPublicKey | sed -n '/^ /{H;d};/sshPublicKey:/x;$g;s/\n *//g;s/sshPublicKey: //gp'
